In [9]:
# Import standard libraries
import pandas as pd
import talib as ta

#Import custom module
import sys
import os
sys.path.insert(0,os.path.abspath("../scripts"))
import finance_analysis as fa
import importlib
importlib.reload(fa)

In [10]:
# Load the dataset
df = pd.read_csv('../data/yfinance_data/AAPL_historical_data.csv')

# Display the first few rows of the dataset
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.098943,469033600,0.0,0.0
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.093781,175884800,0.0,0.0
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.086898,105728000,0.0,0.0
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089049,86441600,0.0,0.0
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.091630,73449600,0.0,0.0

Apply Technical Indicators with TA-Lib

In [15]:
df = fa.ta_indicators(df)
df.head(25)

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA_20,SMA_50,RSI,MACD,MACD_signal,MACD_hist
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.098943,469033600,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.093781,175884800,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.086898,105728000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089049,86441600,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.091630,73449600,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
5,1980-12-19,0.126116,0.126674,0.126116,0.126116,0.097223,48630400,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
6,1980-12-22,0.132254,0.132813,0.132254,0.132254,0.101954,37363200,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7,1980-12-23,0.137835,0.138393,0.137835,0.137835,0.106257,46950400,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8,1980-12-24,0.145089,0.145647,0.145089,0.145089,0.111849,48003200,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
9,1980-12-26,0.158482,0.159040,0.158482,0.158482,0.122173,55574400,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
10,1980-12-29,0.160714,0.161272,0.160714,0.160714,0.123894,93161600,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
11,1980-12-30,0.157366,0.157366,0.156808,0.156808,0.120883,68880000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
12,1980-12-31,0.152902,0.152902,0.152344,0.152344,0.117442,35750400,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
13,1981-01-02,0.154018,0.155134,0.154018,0.154018,0.118732,21660800,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
14,1981-01-05,0.151228,0.151228,0.150670,0.150670,0.116151,35728000,0.0,0.0,NaN,NaN,64.493312,NaN,NaN,NaN
15,1981-01-06,0.144531,0.144531,0.143973,0.143973,0.110989,45158400,0.0,0.0,NaN,NaN,58.970446,NaN,NaN,NaN
16,1981-01-07,0.138393,0.138393,0.137835,0.137835,0.106257,55686400,0.0,0.0,NaN,NaN,54.374496,NaN,NaN,NaN
17,1981-01-08,0.135603,0.135603,0.135045,0.135045,0.104106,39827200,0.0,0.0,NaN,NaN,52.376308,NaN,NaN,NaN
18,1981-01-09,0.142299,0.142857,0.142299,0.142299,0.109698,21504000,0.0,0.0,NaN,NaN,56.819433,NaN,NaN,NaN
19,1981-01-12,0.142299,0.142299,0.141183,0.141183,0.108838,23699200,0.0,0.0,0.138588,NaN,55.954525,NaN,NaN,NaN
20,1981-01-13,0.136719,0.136719,0.136161,0.136161,0.104966,23049600,0.0,0.0,0.138979,NaN,52.110399,NaN,NaN,NaN
21,1981-01-14,0.136719,0.137277,0.136719,0.136719,0.105396,14291200,0.0,0.0,0.139732,NaN,52.500873,NaN,NaN,NaN
22,1981-01-15,0.139509,0.140625,0.139509,0.139509,0.107547,14067200,0.0,0.0,0.141071,NaN,54.498568,NaN,NaN,NaN
23,1981-01-16,0.138951,0.138951,0.138393,0.138393,0.106687,13395200,0.0,0.0,0.142215,NaN,53.528777,NaN,NaN,NaN
24,1981-01-19,0.146763,0.147321,0.146763,0.146763,0.113139,41574400,0.0,0.0,0.143611,NaN,59.368572,NaN,NaN,NaN
25,1981-01-20,0.142857,0.142857,0.142299,0.142299,0.109698,30083200,0.0,0.0,0.144420,NaN,55.372003,NaN,NaN,NaN
26,1981-01-21,0.145089,0.146205,0.145089,0.145089,0.111849,15904000,0.0,0.0,0.145061,NaN,57.306456,NaN,NaN,NaN
27,1981-01-22,0.146763,0.147879,0.146763,0.146763,0.113139,35548800,0.0,0.0,0.145508,NaN,58.469647,NaN,NaN,NaN
28,1981-01-23,0.146763,0.147321,0.146205,0.146205,0.112709,11222400,0.0,0.0,0.145564,NaN,57.903330,NaN,NaN,NaN
29,1981-01-26,0.144531,0.144531,0.143973,0.143973,0.110989,24640000,0.0,0.0,0.144838,NaN,55.584215,NaN,NaN,NaN

In [14]:
# Check the results
print(df[['Close', 'SMA_20']].head(25))

       Close    SMA_20
0   0.128348       NaN
1   0.121652       NaN
2   0.112723       NaN
3   0.115513       NaN
4   0.118862       NaN
5   0.126116       NaN
6   0.132254       NaN
7   0.137835       NaN
8   0.145089       NaN
9   0.158482       NaN
10  0.160714       NaN
11  0.156808       NaN
12  0.152344       NaN
13  0.154018       NaN
14  0.150670       NaN
15  0.143973       NaN
16  0.137835       NaN
17  0.135045       NaN
18  0.142299       NaN
19  0.141183  0.138588
20  0.136161  0.138979
21  0.136719  0.139732
22  0.139509  0.141071
23  0.138393  0.142215
24  0.146763  0.143611

Technical indicators like Simple Moving Average (SMA) require a certain number of data points before they can produce a valid output. For example, a 20-period SMA needs at least 20 data points to calculate the first value. Before that, the result will be NaN.

In [17]:
# Ensure proper column names and data types
df.columns = df.columns.str.lower().str.strip()
for col in ['open', 'high', 'low', 'close', 'volume']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Handle NaNs
df.fillna(method='ffill', inplace=True)
df.dropna(inplace=True)

# Recalculate technical indicators
df['SMA_20'] = ta.SMA(df['close'], timeperiod=20)
df['RSI'] = ta.RSI(df['close'], timeperiod=14)
df['MACD'], df['MACD_signal'], df['MACD_hist'] = ta.MACD(df['close'], fastperiod=12, slowperiod=26, signalperiod=9)

# Verify results
print(df[['close', 'SMA_20', 'RSI', 'MACD', 'MACD_signal', 'MACD_hist']].tail(25))

C:\Users\HP\AppData\Local\Temp\ipykernel_14780\2411849976.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

            close      SMA_20        RSI      MACD  MACD_signal  MACD_hist
10973  209.070007  202.242500  63.268212  6.584845     6.826872  -0.242027
10974  213.250000  203.405499  67.358232  6.578164     6.777130  -0.198966
10975  214.100006  204.596000  68.135240  6.565772     6.734859  -0.169087
10976  210.619995  205.562500  61.663474  6.203632     6.628613  -0.424981
10977  216.750000  206.787500  67.516480  6.338210     6.570533  -0.232322
10978  220.270004  208.099500  70.318783  6.652217     6.586870   0.065348
10979  221.550003  209.459500  71.288745  6.924533     6.654402   0.270131
10980  226.339996  210.983000  74.629962  7.441082     6.811738   0.629344
10981  227.820007  212.650001  75.575738  7.879050     7.025201   0.853850
10982  228.679993  214.239500  76.132520  8.201001     7.260361   0.940640
10983  232.979996  216.232500  78.741969  8.702803     7.548849   1.153954
10984  227.570007  217.253501  68.582565  8.565209     7.752121   0.813088
10985  230.539993  218.127000  70.809208  8.596721     7.921041   0.675680
10986  234.399994  219.135000  73.443524  8.831361     8.103105   0.728256
10987  234.820007  220.251500  73.721422  8.948060     8.272096   0.675964
10988  228.880005  220.862000  63.587172  8.463671     8.310411   0.153260
10989  224.179993  221.356500  56.919750  7.612783     8.170885  -0.558103
10990  224.309998  222.088000  57.053890  6.869748     7.910658  -1.040910
10991  223.960007  222.911501  56.543451  6.181391     7.564804  -1.383414
10992  225.009995  223.755000  57.764268  5.655396     7.182923  -1.527527
10993  218.539993  224.228500  48.687742  4.662717     6.678882  -2.016164
10994  217.490005  224.440500  47.386437  3.748082     6.092722  -2.344640
10995  217.960007  224.633500  48.055700  3.026267     5.479431  -2.453164
10996  218.240005  225.014500  48.476184  2.448591     4.873263  -2.424672
10997  218.800003  225.117001  49.359115  2.012764     4.301163  -2.288399